<?php
declare(strict_types=1);

/**
 * @var \Magento\Backend\Block\Template $block
 * @var Marketplacer\Marketplacer\ViewModel\Adminhtml\Shipment\ShippedFromAddress $viewModel
 */
$viewModel = $block->getViewModel();
$escaper = $viewModel->getEscaper();
$shippedFromAddress = $viewModel->getShippedFromAddress();
?>

<?php if ($shippedFromAddress->getParentId()): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?= $escaper->escapeHtml(__('Ship from address')) ?></span>
        </div>
        <div class="admin__page-section-content">
            <?= $escaper->escapeHtml(__('Address:')) ?> <?= $escaper->escapeHtml($shippedFromAddress->getAddress()) ?>
            <br>
            <?= $escaper->escapeHtml(__('Subaddress:')) ?> <?= $escaper->escapeHtml($shippedFromAddress->getSubaddress()) ?>
            <br>
            <?= $escaper->escapeHtml(__('City:')) ?> <?= $escaper->escapeHtml($shippedFromAddress->getCity()) ?>
            <br>
            <?= $escaper->escapeHtml(__('State short:')) ?> <?= $escaper->escapeHtml($shippedFromAddress->getStateShort()) ?>
            <br>
            <?= $escaper->escapeHtml(__('Country name:')) ?> <?= $escaper->escapeHtml($shippedFromAddress->getCountryName()) ?>
            <br>
            <?= $escaper->escapeHtml(__('Postcode:')) ?> <?= $escaper->escapeHtml($shippedFromAddress->getPostcode()) ?>
        </div>
    </section>
<?php endif; ?>
